// AUTO-GENERATED by scripts/build-orbit-textures.mjs — do not edit by hand.
// Regenerate with: node scripts/build-orbit-textures.mjs

export interface ImageMeta {
    width: number;
    height: number;
    aspect: number;
}

export const imageMeta: Record<string, ImageMeta> = {
    "000033.webp": {
        "width": 1920,
        "height": 2865,
        "aspect": 0.6702
    },
    "Cinestill-50D-plus-Kodak-Endura-2.webp": {
        "width": 1024,
        "height": 1536,
        "aspect": 0.6667
    },
    "Cinestill-50D-plus-Kodak-Endura.webp": {
        "width": 1536,
        "height": 1024,
        "aspect": 1.5
    },
    "Cinestill-800T-plus-Kodak-Endura-2.webp": {
        "width": 1024,
        "height": 1536,
        "aspect": 0.6667
    },
    "Fujicolor-C200-plus-3513.webp": {
        "width": 1273,
        "height": 848,
        "aspect": 1.5012
    },
    "IMG_1150.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_1338.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_1345.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_3218.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_5031.webp": {
        "width": 1920,
        "height": 2881,
        "aspect": 0.6664
    },
    "IMG_5637.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_5725.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_5771.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_5834.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_5895.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_5921.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_6039.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_6613.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_7076.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_7087.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "IMG_7178.webp": {
        "width": 1920,
        "height": 1280,
        "aspect": 1.5
    },
    "IMG_9109.webp": {
        "width": 1920,
        "height": 2880,
        "aspect": 0.6667
    },
    "Kodak-Plus-X-Pan-125-Exp.-1979.webp": {
        "width": 1454,
        "height": 969,
        "aspect": 1.5005
    },
    "Konica-Impresa-50-Exp.2006-plus-Kodak-Endura.webp": {
        "width": 1293,
        "height": 862,
        "aspect": 1.5
    }
};

/** Ring thumbnail (long edge 1024px) used by the 3D scene. */
export const ringTextureUrl = (url: string): string => url.replace('/images/', '/images/ring/');
